autoDetectedPackages:
- io.flutter.plugins
enableAutoDetect: true
entryDisplayConfig: null
funcDisplayConfig: null
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: null
sourceDisplayConfig: null
startOnDebug: null
